{
    'name': 'ARM Rice Mill Management',
    'version': '19.0.1.1.0',
    'summary': 'End-to-End Rice Mill ERP: Contracts, Procurement, Weighbridge, Quality, and Milling',
    'category': 'Manufacturing',
    'website': '',
    'author': 'Abdur Rehman Muhammad',
    'license': 'LGPL-3',
    'depends': ['sale', 'sale_stock', 'purchase', 'purchase_stock', 'stock', 'mail', 'account', 'approval_matrix'],
    'data': [
        'data/crop_years_data.xml',
        'data/sequence_data.xml',
        'security/rice_security_groups.xml',
        'security/ir.model.access.csv',
        'reports/purchase_order_report.xml',
        'reports/payment_certificate_report.xml',
        'reports/gate_pass_report.xml',
        'reports/dispatch_order_report.xml',
        'reports/delivery_certificate_report.xml',
        'views/rice_sales_contract_views.xml',
        'views/purchase_order_views.xml',
        'views/grn_inspection_views.xml',
        'views/gate_pass_views.xml',
        'views/weighbridge_views.xml',
        'views/stock_picking_views.xml',
        'views/payment_certificate_views.xml',
        'views/payment_voucher_views.xml',
        'views/master_data_views.xml',
    ],
    'installable': True,
    'application': True,
}