{
    'name': 'MR Rice Mill Management',
    'version': '1.0',
    'summary': 'Configure and Generate BM Rice Management Report.',
    'description': """
        This module provides a form to create and save configurations for the
        Service Bills Payment Cycle Report and generate it.
    """,
    'category': 'Accounting/Reporting',
    'depends': ['base', 'stock', 'arm_rice_mill', 'purchase', 'account', 'arm_rice_manufacturing',],
    'data': [
        'security/ir.model.access.csv',
        'reports/weighbridge_report.xml',
        'reports/grn_report.xml',
        'reports/ini_grn_report.xml',
        'reports/stock_report.xml',
        'reports/report_design.xml',
        'reports/report_design_grn.xml',
        'reports/product_allowance_report.xml',
        'reports/purchase_summary_report.xml',
        'reports/payment_certificate_summary_report.xml',
        'reports/po_vs_grn_report.xml',
        'reports/corn_contract_report.xml',
        'reports/rice_deduction_report.xml',
        'reports/good_receipt_inspection_report.xml',
        'reports/payment_certificate_date_report.xml',
        'reports/grn_date_wise_report.xml',
        'reports/process_rice_spec_report.xml',
        'reports/brand_production_report.xml',
        'views/weighbridge_view.xml',
        'views/wizard_view.xml',
        'views/wizard_grn.xml',
        'views/product_allowance_view.xml',
        'views/purchase_summary_view.xml',
        'views/payment_certificate_summary_view.xml',
        'views/po_vs_grn_view.xml',
        'views/corn_contract_view.xml',
        'views/rice_deduction_view.xml',
        'views/good_receipt_inspection_view.xml',
        'views/payment_certificate_date_view.xml',
        'views/grn_date_wise_view.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
