# -*- coding: utf-8 -*-

from odoo import models, fields, api, _
from odoo.exceptions import UserError
from typing import Dict, Any, List, Tuple

COMMAND_CREATE_NEW: int = 0

PICKING_INTERNAL: str = 'internal'


class MaterialIssueNote(models.Model):
    _name = 'material.issue.note'
    _description = 'Material Issue Note'
    _inherit = ['mail.thread', 'mail.activity.mixin', 'smart.button.mixin']
    _order = 'id desc'

    name = fields.Char(string='MIN No.', index=True, readonly=True, copy=False,
                       default=lambda self: _('New'))
    document_type = fields.Char(string='Type', default='MIN', readonly=True, copy=False)
    date = fields.Date(string='Date', default=fields.Date.today(), required=True)
    department = fields.Char(string='Department')
    remarks = fields.Text(string='Remarks')

    # Chain: always belongs to a Purchase Indent.
    purchase_indent_id = fields.Many2one(
        'purchase.indent', string='Purchase Indent', required=True, ondelete='restrict',
        readonly=True)

    material_issue_line_ids = fields.One2many('material.issue.note.line', 'issue_note_id', string='Issue Items')

    # Availability check: True when every line's on-hand covers its qty.
    is_fully_available = fields.Boolean(
        string='Fully Available', compute='_compute_is_fully_available', store=False,
        help="True when every line's on-hand quantity covers its required quantity.")
    availability_checked = fields.Boolean(
        string='Availability Checked', copy=False,
        help="Set when the user has run Check Availability at least once.")

    state = fields.Selection([
        ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('done', 'Done'), ('cancel', 'Cancelled'),
    ], string='Status', default='draft', tracking=True)

    purchase_order_ids = fields.One2many('purchase.order', 'material_issue_note_id', string='Purchase Orders')
    purchase_order_count = fields.Integer(string='Purchase Orders', compute='_compute_purchase_order_count')

    # The stock transfer generated by Issue Directly
    issue_picking_id = fields.Many2one('stock.picking', string='Issue Transfer', readonly=True, copy=False)

    @api.model_create_multi
    def create(self, vals_list: List[Dict[str, Any]]) -> 'MaterialIssueNote':
        for vals in vals_list:
            if vals.get('name', _('New')) == _('New'):
                vals['name'] = self.env['ir.sequence'].next_by_code('material.issue.note') or _('New')
        return super().create(vals_list)

    def _compute_purchase_order_count(self) -> None:
        counts = self._get_related_record_count_batch('purchase.order', 'material_issue_note_id')
        for rec in self:
            rec.purchase_order_count = counts.get(rec.id, 0)

    @api.depends('material_issue_line_ids.is_available')
    def _compute_is_fully_available(self) -> None:
        for rec in self:
            lines = rec.material_issue_line_ids.filtered(lambda l: l.product_id)
            rec.is_fully_available = bool(lines) and all(lines.mapped('is_available'))

    def action_confirm(self) -> None:
        for rec in self:
            if not rec.material_issue_line_ids:
                raise UserError(_("Please add at least one item before confirming the Material Issue Note."))
            rec.state = 'confirmed'

    # ==========================================================
    # AVAILABILITY (the branch point of the indent flow)
    # ==========================================================

    def action_check_availability(self) -> None:
        """The branch point: recomputes every line's on-hand vs required
        quantity and flags the note. Fully available -> the user can Issue
        Directly (stock transfer, no purchase). Any line short -> the user
        raises a Purchase Order (PO -> Material Inspection -> GRN -> PC)."""
        self.ensure_one()
        if not self.material_issue_line_ids:
            raise UserError(_("Please add items before checking availability."))

        self.material_issue_line_ids._compute_on_hand_qty()
        self.availability_checked = True

        if self.is_fully_available:
            notification = {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'type': 'success',
                    'title': _("All items available"),
                    'message': _("Every line's on-hand quantity covers its requirement. "
                                 "You can Issue Directly from stock."),
                    'sticky': False,
                },
            }
        else:
            short_lines = self.material_issue_line_ids.filtered(lambda l: not l.is_available)
            notification = {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'type': 'warning',
                    'title': _("Items short in stock"),
                    'message': _("%s item(s) are short: %s. Raise a Purchase Order for the "
                                 "full requirement.",
                                 len(short_lines),
                                 ", ".join(short_lines.mapped('product_id.display_name'))),
                    'sticky': True,
                },
            }
        return notification

    def action_issue_directly(self) -> Dict[str, Any]:
        """Fully-available path: move the stock NOW via an internal transfer
        (stock -> the indent's Location). No PO, no money - the items are
        simply issued from inventory. Validates the transfer immediately;
        the note goes to Done."""
        self.ensure_one()
        if self.state != 'confirmed':
            raise UserError(_("Please confirm the note before issuing directly."))

        if not self.availability_checked:
            raise UserError(_("Please run Check Availability before issuing directly."))

        self.material_issue_line_ids._compute_on_hand_qty()
        if not self.is_fully_available:
            short_lines = self.material_issue_line_ids.filtered(lambda l: not l.is_available)
            raise UserError(_(
                "Cannot issue directly: %s item(s) are short on stock (%s). "
                "Raise a Purchase Order instead.",
                len(short_lines),
                ", ".join(short_lines.mapped('product_id.display_name')),
            ))

        indent = self.purchase_indent_id
        if not indent.location_id:
            raise UserError(_(
                "The Purchase Indent %s has no Location set. The issue destination "
                "is the indent's Location - please set it first.", indent.name))

        picking_type = self.env['stock.picking.type'].search([
            ('code', '=', PICKING_INTERNAL),
            ('company_id', '=', self.env.company.id),
        ], limit=1)
        if not picking_type:
            raise UserError(_("Please configure an internal operation type."))

        stock_location = self.env.ref('stock.stock_location_stock')

        picking = self.env['stock.picking'].create({
            'partner_id': False,
            'picking_type_id': picking_type.id,
            'origin': f"{indent.name} / {self.name}",
            'location_id': stock_location.id,
            'location_dest_id': indent.location_id.id,
        })

        for line in self.material_issue_line_ids.filtered(lambda l: l.product_id and l.product_qty > 0):
            self.env['stock.move'].create({
                'picking_id': picking.id,
                'picking_type_id': picking_type.id,
                'product_id': line.product_id.id,
                'product_uom': line.product_id.uom_id.id,
                'product_uom_qty': line.product_qty,
                'quantity': line.product_qty,
                'picked': True,
                'location_id': stock_location.id,
                'location_dest_id': indent.location_id.id,
                'origin': picking.origin,
            })

        picking.action_confirm()
        picking.action_assign()

        validate_res = picking.button_validate()
        if isinstance(validate_res, dict) and validate_res.get('res_model') == 'stock.immediate.transfer':
            wiz = self.env['stock.immediate.transfer'].with_context(validate_res.get('context', {})).create({})
            wiz.process()

        self.write({
            'issue_picking_id': picking.id,
            'state': 'done',
        })
        return self._open_form_view('stock.picking', picking.id, 'Issue Transfer')

    def action_view_issue_transfer(self) -> Dict[str, Any]:
        self.ensure_one()
        return self._open_form_view('stock.picking', self.issue_picking_id.id, 'Issue Transfer')

    def action_create_purchase_order(self) -> Dict[str, Any]:
        """Short-stock path: the Purchase Order is raised from the note,
        carrying the indent link (vendor comes from the indent). The flow
        then continues PO -> Material Inspection -> GRN -> Payment
        Certificate."""
        self.ensure_one()
        if self.state != 'confirmed':
            raise UserError(_("Please confirm the Material Issue Note before creating a Purchase Order."))

        indent = self.purchase_indent_id
        if not indent.vendor_id:
            raise UserError(_(
                "The linked Purchase Indent %s has no Vendor set. "
                "Please set it before creating a Purchase Order.", indent.name))

        valid_lines = self.material_issue_line_ids.filtered(lambda l: l.product_id and l.product_qty > 0)
        if not valid_lines:
            raise UserError(_("The issue note has no valid item lines to order."))

        order_lines = [(COMMAND_CREATE_NEW, 0, {
            'product_id': line.product_id.id,
            'name': line.description or line.product_id.display_name or line.product_id.name,
            'product_qty': line.product_qty,
            'product_uom_id': line.uom_id.id or line.product_id.uom_id.id,
        }) for line in valid_lines]

        order = self.env['purchase.order'].create({
            'partner_id': indent.vendor_id.id,
            'purchase_indent_id': indent.id,
            'material_issue_note_id': self.id,
            'origin': f"{indent.name} / {self.name}",
            'date_order': fields.Datetime.now(),
            'order_line': order_lines,
        })
        return self._open_form_view('purchase.order', order.id, 'Purchase Order')

    def action_view_purchase_orders(self) -> Dict[str, Any]:
        self.ensure_one()
        return self._open_related_records('purchase.order', 'material_issue_note_id', 'Purchase Orders')

    def action_mark_done(self) -> None:
        for rec in self: rec.state = 'done'

    def action_cancel(self) -> None:
        for rec in self: rec.state = 'cancel'

    def action_reset_to_draft(self) -> None:
        for rec in self: rec.state = 'draft'


class MaterialIssueNoteLine(models.Model):
    _name = 'material.issue.note.line'
    _description = 'Material Issue Note Line'

    issue_note_id = fields.Many2one('material.issue.note', string='Issue Note', required=True, ondelete='cascade')
    product_id = fields.Many2one(
        'product.product', string='Item', required=True,
        domain=[('is_purchase_indent', '=', True)])
    item_code = fields.Char(string='Item Code', related='product_id.default_code', store=True, readonly=True)
    description = fields.Char(string='Item Description')
    uom_id = fields.Many2one('uom.uom', string='Unit',
                             related='product_id.uom_id', store=True, readonly=True)
    product_qty = fields.Float(string='Quantity', required=True, default=1.0)

    # Availability (live): on-hand in the company's stock locations and
    # whether it covers the required quantity.
    on_hand_qty = fields.Float(string='On Hand', compute='_compute_on_hand_qty')
    is_available = fields.Boolean(string='Available', compute='_compute_is_available',
                                  help="True when the on-hand quantity covers this line's quantity.")

    def _compute_on_hand_qty(self) -> None:
        """On-hand across all internal stock locations (company-wide -
        the note does not pin a source location; Check Availability is a
        'do we have it anywhere' question)."""
        for line in self:
            if line.product_id:
                quants = self.env['stock.quant'].read_group(
                    [('product_id', '=', line.product_id.id),
                     ('location_id.usage', '=', 'internal'),
                     ('company_id', '=', self.env.company.id)],
                    ['quantity:sum'],
                    [],
                )
                line.on_hand_qty = quants[0]['quantity'] or 0.0 if quants else 0.0
            else:
                line.on_hand_qty = 0.0

    @api.depends('on_hand_qty', 'product_qty')
    def _compute_is_available(self) -> None:
        for line in self:
            line.is_available = line.product_id and line.on_hand_qty >= line.product_qty